GET http://localhost:5000/product

###
GET http://localhost:5000/product/1

###
POST http://localhost:5000/product
Content-Type: application/json

{
  "nama_barang": "12311121",
  "jenis": "apa cuk",
  "jumlah": 2
}

###
PATCH http://localhost:5000/product/2
Content-Type: application/json

{
  "nama_barang": "paku",
  "jenis": "apa aja",
  "jumlah": 199
}

###
DELETE http://localhost:5000/product/1